name: CICD

on:
  push:
    branches: [ "master" ]

env:
    REGISTRY: roxsross12
    IMAGE_NAME: ${{ github.event.repository.name }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check listar
      run: ls
    - name: docker build vote
      run: |
        cd vote && docker build -t $REGISTRY/$IMAGE_NAME:vote-1.0.0 .
    - name: docker build result
      run: |
        cd result && docker build -t $REGISTRY/$IMAGE_NAME:result-1.0.0 .
    - name: docker build worker
      run: |
        cd worker && docker build -t $REGISTRY/$IMAGE_NAME:worker-1.0.0 .
    - name: docker images
      run: docker images | grep $REGISTRY/$IMAGE_NAME
